### ISSUE TITLE
Viel einfacher

### ISSUE THREAD

**Issue by MartinVollenweider** [MaxiMilli/IModoro#1]
Diese Version ist viel verständlicher für die Studierenden.
Verbesserungsvorschlag #1: Statt
<!DOCTYPE html>
<head>
die von Atom/Brackets generierte Form verwenden:
<!DOCTYPE html>
<html lang="de">
<head>

#2: Zeile 15 gehört weg: <script src="js/pomo_module.js"></script>

**Comment by MaxiMilli** [comment]
Hallo @MartinVollenweider , Danke für die beiden Inputs. Beides ist so geändert...
